export enum SystemRole {
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  SUBDIREC_ACAD = 'SUBDIREC_ACAD',
  JEFE_DIV = 'JEFE_DIV',
  DESARROLLO_ACAD = 'DESARROLLO_ACAD',
  SERVICIOS_ESCOLARES = 'SERVICIOS_ESCOLARES',
  VINCULACION = 'VINCULACION',
  PREFECTO = 'PREFECTO',
  DOCENTE = 'DOCENTE',
  ALUMNO = 'ALUMNO',
}
