export enum Role {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  SERVICIOS_ESCOLARES = 'SERVICIOS_ESCOLARES',
  DOCENTE = 'DOCENTE',
  ALUMNO = 'ALUMNO',
  JEFE = 'JEFE',
  SUBDIRECCION = 'SUBDIRECCION',
  DESARROLLO_ACADEMICO = 'DESARROLLO_ACADEMICO',
}
